language: objective-c
osx_image: xcode9
xcode_project: sdk/PaymentezSDK/PaymentezSDK.xcodeproj
xcode_scheme: PaymentezSDK
script: xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' -project sdk/PaymentezSDK/PaymentezSDK.xcodeproj -scheme PaymentezSDK build test
