language: objective-c
osx_image: xcode9
script : "sh package.sh"
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "build/Release-Universal/PaymentezSDK.framework.zip"
  on:
    repo: guxx/paymentez-ios
