language: objective-c
osx_image: xcode9
script : "sh package.sh"
deploy:

  provider: releases
  api_key: d4cabb7bc97f76e02a673fa1a4baace599698eef
  file: "build/Release-Universal/PaymentezSDK.framework.zip"
  on:
    repo: guxx/paymentez-ios
